apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxi-deployment
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: bharath0812/tomcat:3.0
        ports:
        - containerPort: 8080
