apiVersion: v1
kind: Secret
metadata:
  name: cred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJzdGFsaW4uamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogImMzUmhiR2x1TG14bGJtbHVRR2R0WVdsc0xtTnZiVHBOWVdGdFlXNW5ZV3hoUURFeWMzUT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson